language: java
sudo: false
before_script:
  # Ant build tool configuration
  - cp build.properties.sample build.properties
  - mkdir ./bin
  - sed -i -e "s,jars_dest =,jars_dest =./," build.properties
script:
  - ant run
  - sonar-scanner
env:
  global:
    - classes=JMetadata/classes
    - jars_dest=./
jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.sonar/cache'
addons:
  sonarcloud:
    organization: "welle-github" # the key of the org you chose at step #3
  