language: java
sudo: required
install: true
jdk:
  - oraclejdk8
before_script:
  - chmod +x ./.travis/upload-to-repo.sh
  - sed -i -e 's/\r$//' ./.travis/upload-to-repo.sh
  - sed -i -e "s,\"\${ALLOCINEAPIKEY_VALUE\}\",\"$ALLOCINE_API_KEY\"," ./src/test/java/aka/jmetaagents/test/resource/MetaagentConstants.java
  - sed -i -e "s,\"\${TVDB_API_KEY_VALUE\}\",\"$TVDB_API_KEY\"," ./src/test/java/aka/jmetaagents/test/resource/MetaagentConstants.java
  - sed -i -e "s,\"\${TVDB_USERNAME_VALUE\}\",\"$TVDB_USERNAME\"," ./src/test/java/aka/jmetaagents/test/resource/MetaagentConstants.java
  - sed -i -e "s,\"\${TVDB_USER_KEY_VALUE\}\",\"$TVDB_USER_KEY\"," ./src/test/java/aka/jmetaagents/test/resource/MetaagentConstants.java
  - sed -i -e "s,\"\${THE_MOVIE_DB_API_KEY_VALUE\}\",\"$THE_MOVIE_DB_API_KEY_VALUE\"," ./src/test/java/aka/jmetaagents/test/resource/MetaagentConstants.java
script: 
  - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mkdir -p /home/travis/repository
addons:
  sonarcloud:
    organization: "welle-github" # the key of the org you chose at step #3
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
after_success:
  - mvn -Denv=dev-travis -DperformRelease=true clean deploy
  - ./.travis/upload-to-repo.sh